StoryPlace/StoryPlace/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoryPlace.DataLayer.BusinessObjects.Entities;
using StoryPlace.Web.ViewModels.Group;

namespace StoryPlace.Web.Controllers
{
    [Authorize]
    public class GroupController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var groups = UnitOfWork.GroupRepository.GetGroupList(UserID);

            var viewModel = new GroupListViewModel
            {
                Items = groups
            };

            return View(viewModel);
        }

        [HttpGet]
        public ViewResult Edit(int? id)
        {
            var group = id.HasValue ?
                UnitOfWork.GroupRepository.GetSingleElementById(id)
                : new Group();

            return View(group);

        }

        [HttpPost]
        public ActionResult Edit(Group model)
        {
            if (ModelState.IsValid)
            {
                if(model.ID>0)
                {
                    UnitOfWork.GroupRepository.Update(model);
                }
                else
                {
                    UnitOfWork.GroupRepository.Insert(model);
                }

                return  RedirectToAction("Index");
            }

            return View(model);

        }

        public ActionResult Join(int id)
        {
            UnitOfWork.GroupRepository.JoinUnJoin(UserID,id);

            return RedirectToAction("Index");
        }
    }
}

StoryPlace/StoryPlace/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using StoryPlace.DataLayer.BusinessObjects.Entities;
using StoryPlace.DataLayer.Core.Tools;
using StoryPlace.Web.ViewModels.Story;

namespace StoryPlace.Web.Controllers
{
    [Authorize]
    public class StoryController:BaseController
    {
        public StoryController()
        {
            
        }

        public StoryController(UnitOfWork unitOfWork)
            : base(unitOfWork)
        {
            
        }


        [HttpGet]
        public ActionResult Index()
        {
            var viewModel = new StoryListViewModel
            {
                Stories = UnitOfWork.StoryRepository.GetUserStories(UserID),
            };
                
            return View(viewModel);
        }


        [HttpGet]
        public ViewResult Edit(int ? id)
        {
            //getting story from repository

            var story = id.HasValue ?
                UnitOfWork.StoryRepository.GetSingleStory(id.Value)
                : new Story();
            
            //getting all the groups
            var groups = UnitOfWork.GroupRepository.Get();

            var groupItems = 
                groups.Select(a => new SelectListItem
            {
                Selected = story.GroupIDs.Any(groupId => story.Groups.Any(g1 => g1.ID == groupId)),
                Text = a.Name,
                Value = a.ID.ToString()
            });

            
            var viewModel = new StoryEditViewModel
            {
                Story = story,
                GroupItems = groupItems
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(StoryEditViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                UnitOfWork.StoryRepository.UpsertStory(viewModel.Story);

                return RedirectToAction("Index");
                
            }

            return View(viewModel);
        }

        public ActionResult Detail(int id)
        {
            var story = UnitOfWork.StoryRepository.GetSingleElementById(id);

            return View(story);
        }
    }
}

StoryPlace/StoryPlace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Story Place", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if(Request.IsAuthenticated)
                    { 
                        <li>@Html.ActionLink("My Stories", "Index", "Story")</li>
                        <li>@Html.ActionLink("Groups", "Index", "Group")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Story Place Sample Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>